### ISSUE TITLE
Failed to build on nightly version of compiller

### ISSUE THREAD

**Issue by no111u3** [jonas-schievink/untagged-option#1]
For new update nightly version of compiler we have a build error - https://travis-ci.org/jonas-schievink/untagged-option:
```rust
error[E0740]: unions may not contain fields that need dropping
  --> src/lib.rs:53:5
   |
53 |     pub some: T,
   |     ^^^^^^^^^^^
   |
note: `std::mem::ManuallyDrop` can be used to wrap the type
  --> src/lib.rs:53:5
   |
53 |     pub some: T,
   |     ^^^^^^^^^^^
```

**Comment by jonas-schievink** [comment]
You probably want to use something like `MabyeUninit` instead anyways, since that's already stable.

**Comment by no111u3** [comment]
Thanks for answer, I really want to found everything solutions how to fix build my crate.

**Comment by Rudo2204** [comment]
Hello, I'm fairly new to Rust and is having the same problem on ` rustc 1.40.0-nightly (1423bec54 2019-11-05)`
Is there any solution to fix this error ?

**Comment by jonas-schievink** [comment]
Interesting. What project is using this crate?

The fix is to use MaybeUninit instead.

**Comment by Rudo2204** [comment]
This project specifically: https://github.com/thejpster/stellaris-launchpad
Can you elaborate on how to use MaybeUninit? I'm fairly new, has only learnt the basics syntaxes.

**Comment by jonas-schievink** [comment]
Thanks. I suppose you could also install an older Rust nightly version that still works.

I'll try to look into this in the next couple of days.

**Comment by jonas-schievink** [comment]
0.2.0 of this library fixes the issue, but it required a breaking change, so any users of this crate won't be automatically fixed.

**Comment by jonas-schievink** [comment]
The stellaris-launchpad crate can be made to build by adding this to the Cargo.toml:

```toml

[patch.crates-io]
untagged-option = { git = "https://github.com/jonas-schievink/untagged-option.git", rev = "80adfcf2874848060c14b561d669187c2a7cbacc" }
```

A better fix would be to update its dependencies though. Then it would also run on stable and not even need `untagged-option` at all.
